services:
  web:
    image: nginx
    ports:
      - 86:80
    volumes:
      - /home/erzhan/PhpstormProjects/online-shop/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html

  php-fpm:
    build: ./docker/php
    volumes:
     # - '/home/erzhan/project/environment:/var/www/html'
      - .:/var/www/html

  db:
    image: postgres
    restart: always


  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 54322:5432